# Generated by Django 4.2.1 on 2023-06-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_reviews_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationdetails',
            name='charger',
        ),
        migrations.AddField(
            model_name='stationdetails',
            name='charger1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stationdetails',
            name='charger2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stationdetails',
            name='charger3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stationdetails',
            name='charger4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
