# Generated by Django 4.2.1 on 2023-06-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_stationdetails_charger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationdetails',
            name='charger1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stationdetails',
            name='charger2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stationdetails',
            name='charger3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stationdetails',
            name='charger4',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
